### ISSUE TITLE
Quire/Netlify deploy checklist

### ISSUE THREAD

**Issue by naeluh** [thegetty/quire-docs#184]
- [ ] Add a `netlify.toml` file in the root of the quire directory
There is a lot of info on HUGO's website about some of the specifics of deploying a HUGO site on Netlify. Look here for more information -> https://gohugo.io/hosting-and-deployment/hosting-on-netlify/

```toml
# netlify.toml
# The prefix is the path to your package.json file in your theme
# Change the path of your theme if it is not themes/quire-starter-theme.

# This section is the production configuration and is all you need to deploy
[build]
publish = "public"
command = "npm --prefix themes/quire-starter-theme run build"

[context.production.environment]
HUGO_VERSION = "0.55.4"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

# These next configurations are optional

# This section is the pull request configuration
[context.deploy-preview]
command = "npm --prefix themes/quire-starter-theme run build"

[context.deploy-preview.environment]
HUGO_VERSION = "0.55.4"

# This section is the branch configuration
[context.branch-deploy]
command = "npm --prefix themes/quire-starter-theme run build"

[context.branch-deploy.environment]
HUGO_VERSION = "0.55.4"

# This section is the branch configuration but targets a specific branch and also runs a different command
[context.stage]
command = "npm --prefix themes/quire-starter-theme run build"

[context.stage.environment]
HUGO_VERSION = "0.55.5"
```
Modify `netlify.toml` to work with your HUGO site `publish = "public"` is going to be your build directory and the `npm` script uses a `prefix` to find the path to the `package.json`. At this point we are not using Quire but rather issuing a HUGO command from the CLI. 

- [ ] In your package.json file you can write a script like this

```json
  "scripts": {
     "build": "webpack --config webpack/webpack.config.prod.js && cd ../../ && hugo --minify --config config.yml,config/site.yml"
  },
```
What this script will do is run `webpack` to build assets and then `hugo` to build the site.

- [ ] Add this to `site.yml`

```yml
baseURL: "https://www.example.com/whatever-url-here-or-nothing/"
canonifyURLs: true
```
